steps:
# Install
- name: 'gcr.io/cloud-builders/npm:node-16'
  args: ['install']
# Test
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['run', 'test:unit']
# Build
- name: 'gcr.io/cloud-builders/npm:node-16'
  args: ['run', 'build']
# Deploy
- name: 'gcr.io/test-project-dev-359015/firebase'
  args: ['deploy', 'project=test-project-dev-359015', '--debug']